// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVyLWisk_tC03Jkb2AF9qlnkBTteGtn34',
    appId: '1:354580440838:web:caca8b9bf05f29bf106087',
    messagingSenderId: '354580440838',
    projectId: 'besta-f6f68',
    authDomain: 'besta-f6f68.firebaseapp.com',
    storageBucket: 'besta-f6f68.firebasestorage.app',
    measurementId: 'G-XJH8FWVQ7D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkq27NWcXeihqD_fQEBt8xmQXkABizXxU',
    appId: '1:354580440838:android:87e65bcdda66f273106087',
    messagingSenderId: '354580440838',
    projectId: 'besta-f6f68',
    storageBucket: 'besta-f6f68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT1idAXrC_e19txIH3mf-n87W1Q_H4bi8',
    appId: '1:354580440838:ios:e1c6be692f2578f3106087',
    messagingSenderId: '354580440838',
    projectId: 'besta-f6f68',
    storageBucket: 'besta-f6f68.firebasestorage.app',
    androidClientId: '354580440838-radro45d8j74dqu8qr5puvifqkminfoo.apps.googleusercontent.com',
    iosClientId: '354580440838-7kr6do7pc8hcdgujjl5fvarqn3he7er3.apps.googleusercontent.com',
    iosBundleId: 'com.example.besta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT1idAXrC_e19txIH3mf-n87W1Q_H4bi8',
    appId: '1:354580440838:ios:e1c6be692f2578f3106087',
    messagingSenderId: '354580440838',
    projectId: 'besta-f6f68',
    storageBucket: 'besta-f6f68.firebasestorage.app',
    androidClientId: '354580440838-radro45d8j74dqu8qr5puvifqkminfoo.apps.googleusercontent.com',
    iosClientId: '354580440838-7kr6do7pc8hcdgujjl5fvarqn3he7er3.apps.googleusercontent.com',
    iosBundleId: 'com.example.besta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVyLWisk_tC03Jkb2AF9qlnkBTteGtn34',
    appId: '1:354580440838:web:867d4ca60658e40c106087',
    messagingSenderId: '354580440838',
    projectId: 'besta-f6f68',
    authDomain: 'besta-f6f68.firebaseapp.com',
    storageBucket: 'besta-f6f68.firebasestorage.app',
    measurementId: 'G-K1CHC6ZH8H',
  );

}